# Generated by Django 3.2.8 on 2021-12-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('imagen', models.ImageField(upload_to='accesorios')),
            ],
        ),
        migrations.CreateModel(
            name='Caras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('imagen', models.ImageField(upload_to='caras')),
            ],
        ),
        migrations.CreateModel(
            name='Vestuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('imagen', models.ImageField(upload_to='vestuario')),
            ],
        ),
    ]
