# Generated by Django 3.2.8 on 2021-12-06 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_certamen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certamen',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 12, 6)),
        ),
        migrations.AlterField(
            model_name='certamen',
            name='hora',
            field=models.CharField(choices=[('b1', '8:15-9:25'), ('b2', '9:35-10:45'), ('b3', '10:55-12:05'), ('b4', '12:15-13:25'), ('b5', '14:30-15:40'), ('b6', '15:50-17:00'), ('b7', '17:10-18:20'), ('b8', '18:30-19:40'), ('b9', '19:50-21:00'), ('b10', '21:10-22:20')], default='b1', max_length=20),
        ),
    ]
