# Generated by Django 3.2.8 on 2021-12-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_exp_nivel'),
        ('perfiles', '0005_auto_20211207_0316'),
    ]

    operations = [
    ]
