# Generated by Django 3.2.8 on 2021-11-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('b12', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], max_length=6)),
                ('b34', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], max_length=6)),
                ('b56', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], max_length=6)),
                ('b78', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], max_length=6)),
                ('b910', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], max_length=6)),
                ('b1112', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], max_length=6)),
                ('b1314', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], max_length=6)),
                ('b1516', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], max_length=6)),
                ('b1718', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], max_length=6)),
                ('b1920', models.CharField(choices=[('L', 'Libre'), ('O', 'Ocupado')], max_length=6)),
            ],
        ),
    ]
