# Generated by Django 3.2.8 on 2021-11-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_auto_20211121_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario_ocupado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('b1', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='horario',
        ),
    ]
