# Generated by Django 3.2.8 on 2021-11-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20211121_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario_ocupado',
            name='b10',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AddField(
            model_name='horario_ocupado',
            name='b2',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AddField(
            model_name='horario_ocupado',
            name='b3',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AddField(
            model_name='horario_ocupado',
            name='b4',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AddField(
            model_name='horario_ocupado',
            name='b5',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AddField(
            model_name='horario_ocupado',
            name='b6',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AddField(
            model_name='horario_ocupado',
            name='b7',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AddField(
            model_name='horario_ocupado',
            name='b8',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AddField(
            model_name='horario_ocupado',
            name='b9',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='horario_ocupado',
            name='b1',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
    ]
