# Generated by Django 3.2.8 on 2021-11-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_auto_20211121_2358'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horario_ocupado',
            new_name='Horario',
        ),
    ]
