# Generated by Django 3.2.8 on 2021-11-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_auto_20211122_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ramo',
            old_name='name',
            new_name='ramo',
        ),
        migrations.AlterField(
            model_name='horario',
            name='b1',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b10',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b2',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b3',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b4',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b5',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b6',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b7',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b8',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b9',
            field=models.CharField(choices=[('ocupado', 'Ocuapado'), ('libre', 'Libre')], default='libre', max_length=20),
        ),
    ]
