# Generated by Django 3.2.8 on 2021-11-28 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Test', '0008_descanso'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario', to=settings.AUTH_USER_MODEL),
        ),
    ]
