# Generated by Django 3.2.8 on 2021-11-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0012_auto_20211128_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='ramo',
            name='dificultad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
