# Generated by Django 3.2.8 on 2021-11-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0013_ramo_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramo',
            name='dificultad',
            field=models.IntegerField(choices=[('1', 'Pf, facilísimo'), ('2', 'Fácil'), ('3', 'Medio'), ('4', 'Difícil'), ('5', 'Muy difícil')], null=True),
        ),
    ]
