# Generated by Django 3.2.8 on 2021-11-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0014_alter_ramo_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramo',
            name='dificultad',
            field=models.CharField(choices=[('Pf, facilísimo', 'Pf, facilísimo'), ('Fácil', 'Fácil'), ('Medio', 'Medio'), ('Difícil', 'Difícil'), ('Muy difícil', 'Muy difícil')], max_length=40, null=True),
        ),
    ]
