# Generated by Django 3.2.8 on 2021-12-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0015_alter_ramo_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='b1',
            field=models.CharField(choices=[('Ocupado', 'Ocuapado'), ('Libre', 'Libre')], default='Libre', max_length=20, verbose_name='8:15-9:25'),
        ),
    ]
