# Generated by Django 3.2.8 on 2021-12-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0016_alter_horario_b1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='b10',
            field=models.CharField(choices=[('Ocupado', 'Ocuapado'), ('Libre', 'Libre')], default='Libre', max_length=20, verbose_name='21:10-22:20'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b2',
            field=models.CharField(choices=[('Ocupado', 'Ocuapado'), ('Libre', 'Libre')], default='Libre', max_length=20, verbose_name='9:35-10:45'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b3',
            field=models.CharField(choices=[('Ocupado', 'Ocuapado'), ('Libre', 'Libre')], default='Libre', max_length=20, verbose_name='10:55-12:05'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b4',
            field=models.CharField(choices=[('Ocupado', 'Ocuapado'), ('Libre', 'Libre')], default='Libre', max_length=20, verbose_name='12:15-13:25'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b5',
            field=models.CharField(choices=[('Ocupado', 'Ocuapado'), ('Libre', 'Libre')], default='Libre', max_length=20, verbose_name='14:30-15:40'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b6',
            field=models.CharField(choices=[('Ocupado', 'Ocuapado'), ('Libre', 'Libre')], default='Libre', max_length=20, verbose_name='15:50-17:00'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b7',
            field=models.CharField(choices=[('Ocupado', 'Ocuapado'), ('Libre', 'Libre')], default='Libre', max_length=20, verbose_name='17:10-18:20'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b8',
            field=models.CharField(choices=[('Ocupado', 'Ocuapado'), ('Libre', 'Libre')], default='Libre', max_length=20, verbose_name='18:30-19:40'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='b9',
            field=models.CharField(choices=[('Ocupado', 'Ocuapado'), ('Libre', 'Libre')], default='Libre', max_length=20, verbose_name='19:50-21:00'),
        ),
    ]
