# Generated by Django 3.2.8 on 2021-12-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0018_auto_20211204_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramo',
            name='dificultad',
            field=models.IntegerField(choices=[(1, 'Pf, facilísimo'), (2, 'Fácil'), (3, 'Medio'), (4, 'Difícil'), (5, 'Muy difícil')], max_length=40, null=True),
        ),
    ]
